trigger: none

pool:
  vmImage: 'ubuntu-26.04'

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: Run_Test
        displayName: Run unit tests and coverage
        steps:
          - script: |
              pip install -r requirements.txt
            displayName: Install Python requirements

          - script: |
              pytest --junitxml=test-results.xml --cov=. --cov-branch --cov-report xml:test-coverage.xml --cov-config=.coveragerc
            displayName: Run pytest for unit test and coverage

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/test-results.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)'
              testRunTitle: 'Python Pytest Results'
            condition: succeededOrFailed()
            displayName: 'Publish Test Results'
            
          - task: PublishCodeCoverageResults@2
            inputs:
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/test-coverage.xml'
            displayName: 'Publish Code Coverage'
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildJob
        displayName: Sample build job
        steps:
          - script: |
              pwd